Kanban/Models/Manager.cs
using System;
using System.Collections.Generic;

namespace Kanban.Models
{
  public class Manager
  {
    public int ManagerId { get; set;}
    public string Name { get; set; }
    public string ContactInfo {get; set;}
    public DateTime RegisteredDate {get; set;}
    public string Position {get; set;} //desining positions
    public bool CurrentStatus {get; set;}
    //public virtual ApplicationUser User {get; set;}
    public ICollection<ProjectManager> Projects {get; set;}
    public virtual ICollection<ToDoList> ToDoLists {get; set;}

    public Manager()
    {
      this.Projects = new HashSet<ProjectManager> ();
      this.ToDoLists = new HashSet<ToDoList>();
    }
  }
}

Kanban/Controllers/ManagersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Kanban.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Kanban.Controllers
{
  public class ManagersController : Controller
  {
    private readonly KanbanContext _db;
    public ManagersController(KanbanContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Managers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Manager manager, int ProjectId)
    {
    _db.Managers.Add(manager);
    if (ProjectId != 0)
    {
      _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
    }
    _db.SaveChanges();
    return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisManager = _db.Managers
          .Include(manager => manager.ToDoLists)
          .Include(manager => manager.Projects)
          .ThenInclude(join => join.Project)
          .FirstOrDefault(manager => manager.ManagerId == id);
      return View(thisManager);
    }

    public ActionResult Edit(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View(thisManager);
    }

    [HttpPost]
    public ActionResult Edit(Manager manager, int ProjectId)
    {
      if (ProjectId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
      }
      _db.Entry(manager).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddProject(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View(thisManager);
    }

    [HttpPost]
    public ActionResult AddProject(Manager manager, int ProjectId)
    {
      if (ProjectId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      return View(thisManager);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      _db.Managers.Remove(thisManager);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteProject(int joinId)
    {
      var joinEntry = _db.ProjectManagers.FirstOrDefault(entry => entry.ProjectManagerId == joinId);
      _db.ProjectManagers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Kanban/Controllers/ProjectsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Kanban.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Kanban.Controllers
{
  public class ProjectsController : Controller
  {
    private readonly KanbanContext _db;

    public ProjectsController(KanbanContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Project> model = _db.Projects.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Project project)
    {
      _db.Projects.Add(project);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisProject = _db.Projects
          .Include(project => project.ToDoLists) //keep an eye on this;
          .Include(project => project.Managers)
          .ThenInclude(join => join.Manager)
          .FirstOrDefault(project => project.ProjectId == id);
      return View(thisProject);
    }

    public ActionResult Edit(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId ==id);
      return View(thisProject);
    }

    [HttpPost]
    public ActionResult Edit(Project project)
    {
      _db.Entry(project).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      return View(thisProject);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      _db.Projects.Remove(thisProject);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AssignPeople(int id)
    {

      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      var a = _db.Managers.Where(x => x.CurrentStatus == true);

      ViewBag.ManagerId = new SelectList(a, "ManagerId", "Name");
      return View(thisProject);
    }

    [HttpPost]
    public ActionResult AssignPeople(Project project, int ManagerId)
    {
      if (ManagerId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ManagerId = ManagerId, ProjectId = project.ProjectId});
      }
      _db.SaveChanges();

      return RedirectToAction("Details", new {id = project.ProjectId});
    }

    
  } 
}

Kanban/Views/Managers/AddProject.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Manager

<div class="managerAddProject">
  <h1><strong>Add Project to this manager : @Html.DisplayFor(model => model.Name)</strong></h1>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.ManagerId)

    @Html.Label("Assign Project")
    @Html.DropDownList("ProjectId")

    <input type="submit" value="Save">
  }
</div>

Kanban/Views/Managers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Manager

<div class="managerCreate">
  <h1><strong>Add a new crew</strong></h1>
  <hr>
  @using (Html.BeginForm())
  {

    <label asp-for="Name">Crew Name</label>
    <input asp-for="Name" type="text" class="form-control">

    <label asp-for="ContactInfo">Contact</label>
    <input asp-for="ContactInfo" type="text" class="form-control" maxlength="10"> 

    <label asp-for="Position">Position</label>
    <input asp-for="Position" type="text" class="form-control">

    <label asp-for="RegisteredDate">Due Date</label>
    <input asp-for="RegisteredDate" type="date" class="form-control">

    <label asp-for="CurrentStatus">Is this crew Active?</label>
    <input asp-for="CurrentStatus" type="checkbox" value="true">

    @* <label asp-for="ProjectId">Assign</label>
    <select id="ProjectId" asp-items="ViewBag.ProjectId" class="form-control"></select> *@
    <br>
    @Html.Label("Assign this manager to a project")
    @Html.DropDownList("ProjectId")
    <hr>
    <input type="submit" value="Add new manager" class="w3-button w3-green w3-round-large">
  }
</div>

Kanban/Views/Managers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Manager

<div class="managerDelete">
  <h1><strong>Delete this manager?</strong></h1>

  @Html.DisplayNameFor(model=>model.Name) : @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete">
  }

</div>

Kanban/Views/Managers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Manager

<div class="managerDetails">
  <h1><strong>Crew Details</strong></h1>

  <hr>
  <p>Crew Name: @Model.Name</p>
  <p>Contact : @Model.ContactInfo</p>
  <p>Position : @Model.Position</p>
  <p>Registered Date: @Model.RegisteredDate.Month/@Model.RegisteredDate.Day/@Model.RegisteredDate.Year</p>
  <p>Current Status : 
    @if (@Model.CurrentStatus == true)
    {
      <span class="checkmark">✔</span>
    }
    else 
    {
      <span class="wrongmark">✘</span>
    }
  </p>
  <hr>
  @if(@Model.Projects.Count == 0)
  {
    <h3>No projects has been assigned to this manager</h3>
    //<p>@Html.ActionLink("Assign project", "")</p>
  }
  else
  {
    <h3>@Html.DisplayFor(model => model.Name) manages projects:</h3>
    @foreach(var join in Model.Projects)
    {

      <h3>@Html.ActionLink($"{join.Project.ProjectName}", "Details", "Projects", new {id = join.Project.ProjectId })</h3>

      @using (Html.BeginForm("DeleteProject", "Managers"))
      {
        @Html.Hidden("joinId", @join.ProjectManagerId)
        <input type="submit" value="Delete">
      }
    }
  }
  <hr>
  <p>@Html.ActionLink("Edit Manager", "Edit", new {id =Model.ManagerId})</p>
  <p>@Html.ActionLink("Delete Manager", "Delete", new {id =Model.ManagerId})</p>
</div>

Kanban/Views/Managers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Manager

<div class="managerEdit">
  <h1><strong>Edit Crew</strong></h1>
  <hr>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.ManagerId)

    @Html.Label("Crew Name")
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @type="text", @class="form-control" } })

    @Html.Label("Contact")
    @Html.EditorFor(model => model.ContactInfo, new { htmlAttributes = new { @type="text", @class="form-control" } })

    @Html.Label("Position")
    @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @type="text", @class="form-control" } })

    @Html.Label("Registered Date")
    @Html.TextBoxFor(model => model.RegisteredDate, "{0:MM-dd-yyyy}", new { @class = "form-control"})

    @Html.Label("Is this crew Active?")
    @Html.CheckBoxFor(model => model.CurrentStatus, new { htmlAttributes = new { @value=true, @class = "form-control" } })
    <br>
    @Html.Label("Change Project")
    @Html.DropDownList("ProjectId")
    <hr>
    <input type="submit" value="Save" class="w3-button w3-green w3-round-large">
  }
</div>

Kanban/Views/Managers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Kanban.Models;
@model List<Kanban.Models.Manager>;

<div class="managerIndex">
  <h1><strong>Managers</strong></h1>

  @if(@Model.Count == 0)
  {
    <h3>Managers are not in data yet.</h3>

    <p>@Html.ActionLink("Add new manager", "Create")</p>
  }
  else
  {
    @foreach(Manager manager in Model)
    {
      <h3>@Html.ActionLink($"{manager.Name}", "Details", new { id = manager.ManagerId })</h3>
    }

    <p>@Html.ActionLink("Add new manager", "Create")</p>
  }
</div>