Kanban/Models/Project.cs
using System;
using System.Collections.Generic;


namespace Kanban.Models
{
  public class Project
  {
    public int ProjectId {get; set;}
    public string ProjectName {get; set;}
    public string Content {get; set;}
    public DateTime KickOffDate {get; set;}
    public DateTime DueDate {get; set;}
    public bool ActiveStatus {get; set;}
    public virtual ApplicationUser User {get; set;}
    public ICollection<ProjectManager> Managers {get; set;}
    public virtual ICollection<ToDoList> ToDoLists {get; set;}
    public Project()
    {
      this.Managers = new HashSet<ProjectManager> ();
      this.ToDoLists = new HashSet<ToDoList> ();
    }
  }
}

Kanban/Controllers/ManagersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Kanban.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Kanban.Controllers
{
  public class ManagersController : Controller
  {
    private readonly KanbanContext _db;
    public ManagersController(KanbanContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Managers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Manager manager, int ProjectId)
    {
    _db.Managers.Add(manager);
    if (ProjectId != 0)
    {
      _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
    }
    _db.SaveChanges();
    return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisManager = _db.Managers
          .Include(manager => manager.ToDoLists)
          .Include(manager => manager.Projects)
          .ThenInclude(join => join.Project)
          .FirstOrDefault(manager => manager.ManagerId == id);
      return View(thisManager);
    }

    public ActionResult Edit(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View(thisManager);
    }

    [HttpPost]
    public ActionResult Edit(Manager manager, int ProjectId)
    {
      if (ProjectId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
      }
      _db.Entry(manager).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddProject(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      return View(thisManager);
    }

    [HttpPost]
    public ActionResult AddProject(Manager manager, int ProjectId)
    {
      if (ProjectId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ProjectId = ProjectId, ManagerId = manager.ManagerId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      return View(thisManager);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == id);
      _db.Managers.Remove(thisManager);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteProject(int joinId)
    {
      var joinEntry = _db.ProjectManagers.FirstOrDefault(entry => entry.ProjectManagerId == joinId);
      _db.ProjectManagers.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Kanban/Controllers/ProjectsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Kanban.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Kanban.Controllers
{
  public class ProjectsController : Controller
  {
    private readonly KanbanContext _db;

    public ProjectsController(KanbanContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Project> model = _db.Projects.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Project project)
    {
      _db.Projects.Add(project);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisProject = _db.Projects
          .Include(project => project.ToDoLists) //keep an eye on this;
          .Include(project => project.Managers)
          .ThenInclude(join => join.Manager)
          .FirstOrDefault(project => project.ProjectId == id);
      return View(thisProject);
    }

    public ActionResult Edit(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId ==id);
      return View(thisProject);
    }

    [HttpPost]
    public ActionResult Edit(Project project)
    {
      _db.Entry(project).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      return View(thisProject);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      _db.Projects.Remove(thisProject);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AssignPeople(int id)
    {

      var thisProject = _db.Projects.FirstOrDefault(project => project.ProjectId == id);
      var a = _db.Managers.Where(x => x.CurrentStatus == true);

      ViewBag.ManagerId = new SelectList(a, "ManagerId", "Name");
      return View(thisProject);
    }

    [HttpPost]
    public ActionResult AssignPeople(Project project, int ManagerId)
    {
      if (ManagerId != 0)
      {
        _db.ProjectManagers.Add(new ProjectManager() { ManagerId = ManagerId, ProjectId = project.ProjectId});
      }
      _db.SaveChanges();

      return RedirectToAction("Details", new {id = project.ProjectId});
    }

    
  } 
}

Kanban/Controllers/ToDoListsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Kanban.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Kanban.Controllers
{
  public class ToDoListsController : Controller
  {
    private readonly KanbanContext _db;

    public ToDoListsController(KanbanContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<ToDoList> model = _db.ToDoLists
      .Include(todolists => todolists.Project)
      .Include(todolists => todolists.Status)
      .Include(todolists => todolists.Manager)
      .ToList();
      return View(model);
    }

    public ActionResult Create(int ProjectId)
    {
      Console.WriteLine("ProjectId is");
      Console.WriteLine(ProjectId);
      ViewBag.ProjectId = ProjectId;
      ViewBag.StatusId = new SelectList(_db.Statuses, "StatusId", "StatusName");
      ViewBag.ManagerId = new SelectList(_db.Managers, "ManagerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(ToDoList todolist)
    {
      _db.ToDoLists.Add(todolist);
      _db.SaveChanges();
      return RedirectToAction("Index"); // set page to projectDetails
    }

    public ActionResult Details(int id)
    {
      ToDoList thisToDoList = _db.ToDoLists.FirstOrDefault(todolists => todolists.ToDoListId == id);
      Status thisStatus = _db.Statuses.FirstOrDefault(status => status.StatusId == thisToDoList.StatusId);
      Manager thisManager = _db.Managers.FirstOrDefault(manager => manager.ManagerId == thisToDoList.ManagerId);
      ViewBag.StatusName = thisStatus.StatusName;
      ViewBag.Name = thisManager.Name;
      return View(thisToDoList);
    }

    public ActionResult Edit(int id)
    {
      var thisToDoList = _db.ToDoLists.FirstOrDefault(todolists => todolists.ToDoListId == id);
      ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "ProjectName");
      ViewBag.StatusId = new SelectList(_db.Statuses, "StatusId", "StatusName");
      ViewBag.ManagerId = new SelectList(_db.Managers, "ManagerId", "Name");
      return View(thisToDoList);
    }

    [HttpPost]
    public ActionResult Edit(ToDoList todolist)
    {
      _db.Entry(todolist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisToDoList = _db.ToDoLists.FirstOrDefault(todolists => todolists.ToDoListId == id);
      return View(thisToDoList);
    }

    [HttpPost,ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisToDoList = _db.ToDoLists.FirstOrDefault(todolists => todolists.ToDoListId == id);
      _db.ToDoLists.Remove(thisToDoList);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Kanban/Views/Projects/AssignPeople.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Project

<div class="projectAssignPeople">
  <h1><strong>Assign people to this project : @Html.DisplayFor(model => model.ProjectName)</strong></h1>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.ProjectId)

    @Html.Label("Assign People")
    @Html.DropDownList("ManagerId")

    <input type="submit" value="Save" class="w3-button w3-green w3-round-large">
  }
</div>

Kanban/Views/Projects/Create.cshtml
@model Kanban.Models.Project

@{
  Layout = "_Layout";
}

<div class="projectCreate">
  <h1><strong>Add a new Project</strong></h1>

  @using (Html.BeginForm())
  {
    <label asp-for="ProjectName" class="caption">Project Name</label>
    <input asp-for="ProjectName" class="form-control">

    <label asp-for="Content">Description</label>
    <textarea asp-for="Content" class="form-control"></textarea>

    <label asp-for="KickOffDate">Kick Off Date</label>
    <input asp-for="KickOffDate" type="date" class="form-control">
    
    <label asp-for="DueDate">Due Date</label>
    <input asp-for="DueDate" type="date" class="form-control">

    <label asp-for="ActiveStatus">Is this Project Active?</label>
    <input asp-for="ActiveStatus" type="checkbox" value="true">
    <br>
    <input type="submit" value="Add new product" class="w3-button w3-green w3-round-large">
  }
</div>

Kanban/Views/Projects/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Project

<div class="productDelete">
  <h1><strong>Delete this Project?</strong></h1>

  @Html.DisplayNameFor(model => model.ProjectName) : @Html.DisplayFor(model => model.ProjectName)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="w3-button w3-green w3-round-large">
  }

  @Html.ActionLink("Back to project list", "Index")
</div>

Kanban/Views/Projects/Details.cshtml
@{
  Layout = "_Layout";
}

@using Kanban.Models;
@model Kanban.Models.Project;

<div class="projectDetails">
  <h1><strong>Project Details</strong></h1>
  
  <hr>
  <h3>About Project @Html.DisplayFor(model => model.ProjectName)</h3>
  <p>Project Name: @Model.ProjectName</p>
  <p>Description: @Model.Content</p>
  <p>Id is @Model.ProjectId</p>
  <p>Kikc Off Date: @Model.KickOffDate.Month/@Model.KickOffDate.Day/@Model.KickOffDate.Year</p>
  <p>Due Date: @Model.DueDate.Month/@Model.DueDate.Day/@Model.DueDate.Year</p>
  <p>Project Active : 
    @if (@Model.ActiveStatus == true)
    {
      <span class="checkmark">✔</span>
    }
    else 
    {
      <span class="wrongmark">✘</span>
    }
  </p>
  <hr>
  
  @if(@Model.ToDoLists.Count == 0)
  {
    <h3>There are no To Do assigned yet.</h3>
    @Html.ActionLink("Add Tasks", "Create", "ToDoLists", new { ProjectId = Model.ProjectId })
  }
  else
  {
    <h2>Work Items: </h2>
    @foreach(ToDoList todoList in Model.ToDoLists)
    {
      <h3>@Html.ActionLink(@todoList.Name, "Details", "ToDoLists", new { @class = "linkStyle", id = todoList.ToDoListId })</h3>
    }
    Console.WriteLine("Project Id is///// ");
    Console.WriteLine(Model.ProjectId);
    Console.WriteLine(Model.ProjectName);
    @Html.ActionLink("Add Tasks", "Create", "ToDoLists", new { ProjectId = Model.ProjectId })
  }
  <hr>
  @if(Model.Managers.Count == 0)
  {
    <h3>There are no peole assinged on this product yet.</h3>
    @Html.ActionLink("Assign people to this project", "AssignPeople", new { id = Model.ProjectId })
  }
  else
  {
    <h2>Team Crews:</h2>
    @foreach(var join in Model.Managers)
    {
      <h3>@Html.ActionLink(@join.Manager.Name, "Details", "Managers", new { @class = "linkStyle", id = @join.Manager.ManagerId })</h3>
    }
    @Html.ActionLink("Assign people to this project", "AssignPeople", new { id = Model.ProjectId})
  }
  
  <hr>
  
  <p>@Html.ActionLink("Edit Product", "Edit", new { id = Model.ProjectId })</p>
  <p>@Html.ActionLink("Delete Product", "Delete", new { id = Model.ProjectId })</p>
  <button id="button1" text="button">click!</button>
</div>

@* jquery *@
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $("#button1").click(function() {
      alert("hellow world!")
    })
  })
</script>

Kanban/Views/Projects/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Kanban.Models.Project

<div class="projectEdit">

  <h1><strong>Edit this project</strong></h1>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.ProjectId)

    @Html.Label("Project Name")
    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @type="text", @class="form-control" } })

    @Html.Label("Description")
    @Html.TextAreaFor(model => model.Content, new { @type="text", @class="form-control"})

    @Html.Label("Kick Off Date")
    @Html.TextBoxFor(model => model.KickOffDate, "{0:MM-dd-yyyy}", new { @class = "form-control"})

    @Html.Label("Due Date")
    @Html.TextBoxFor(model => model.DueDate, "{0:MM-dd-yyyy}", new { @class = "form-control"})
    
    @Html.Label("Is this Project Active?")
    @Html.CheckBoxFor(model => model.ActiveStatus, new { htmlAttributes = new { @value=true, @class = "form-control" } })
    <br>
    <input type="submit" value="Save" class="w3-button w3-green w3-round-large">
  }

  <p>@Html.ActionLink("Back to project list", "Index")</p>
</div>

Kanban/Views/Projects/Index.cshtml
@{
  Layout = "_Layout";
}

@using Kanban.Models;
@model List<Kanban.Models.Project>;

<div class="projectIndex">

  <h1><strong>Projects</strong></h1>

  @if (@Model.Count == 0)
  {
    <h3>No Projects have been added yet!</h3>
  }
  else
  {
    
    @foreach(Project project in Model)
    {
      
      if(project.ActiveStatus == true)
      {
        //style="border: 2px solid green"
      <div class="activeProjects" >
        <p style="background-color: #1e90ff; color: white; text-align: center; padding: 2px; height: 30px">Active Project<p>
        <h3>@Html.ActionLink($"{project.ProjectName}", "Details", new {id = project.ProjectId })</h3>
      </div>
      }
      else
      {
        <p style="background-color: #FA8072; color: white; text-align: center; padding: 2px; height: 30px">Inactive Projects</p>
        <div class="completedProjects">
          
          <h3>@Html.ActionLink($"{project.ProjectName}", "Details", new {id = project.ProjectId })</h3>
        </div>
      }   
    }
  }

  <p>@Html.ActionLink("Add new Project", "Create")</p>
  
</div>